/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.netflix.spinnaker.gradle.pf4j

import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Functional test for the 'com.netflix.spinnaker.gradle.pf4j.spinnakerpf4j' plugin.
 */
class SpinnakerPf4jGradlePluginFunctionalTest {
    @Test fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionaltest")
        projectDir.mkdirs()
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('com.netflix.spinnaker.gradle.pf4j.spinnakerpf4j')
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("computeChecksum")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("Nothing to checksum!!"))
    }
}
